framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/lib/CMSBundle/Resources/translations'
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
