twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig']
    paths:
        '%kernel.project_dir%/templates': Templates
        "%kernel.project_dir%/lib/CMSBundle/Resources/": CMSBundleViews
    globals:
        user_block: SonataAdminBundle:Block:user_block.html.twig'
        locales: '%locales%'
        recaptcha_site_key: '%env(EWZ_RECAPTCHA_SITE_KEY)%'