INSERT INTO `comment_ca_marche_block` (`id`, `img`, `title`, `description`, `btn1text`, `btn1link`, `btn2text`, `btn2link`, `lang`, `background_color`, `type`, `updated_at`, `btn1target`, `btn2target`) VALUES
(95, '5d399d0653f59032178193.jpg', 'Vous êtes Entrepreneur ?', '<ul>\r\n	<li>Inscrivez-vous et soumettez votre projet, c&rsquo;est facile et intuitif.</li>\r\n	<li>B&eacute;n&eacute;ficiez d&rsquo;une revue professionnelle de votre proposition de valeur, c&rsquo;est gratuit !</li>\r\n	<li>une fois le projet retenu, il sera publi&eacute; et b&eacute;n&eacute;ficiera d&rsquo;une exposition totale &agrave;&nbsp;nos partenaires et r&eacute;seaux d&rsquo;investisseurs.</li>\r\n</ul>', 'Accédez à votre espace', '/fr/startuper/project/dashboard', 'En savoir plus', '/fr/pages/comment-ca-marche/startupers', 'fr', '#2C3E50', 'startuper', '2021-01-20 15:12:54', '_self', '_self'),
(96, '5d399d130b9b9975259105.jpg', 'Founder', '<ul>\r\n	<li>Register and submit your project. Easy and intuitive.</li>\r\n	<li>Get a&nbsp;professional review of your value proposition - it&#39;s <strong>FREE</strong>!</li>\r\n	<li>Once the project is selected, it&#39;s&nbsp;published and gets total exposure among our&nbsp;partners and networks of investors.</li>\r\n</ul>', 'Access Dashboard', '/en/startuper/project/dashboard', 'Learn more', '/en/pages/1092-comment-ca-marche-startupers', 'en', '#2C3E50', 'startuper', '2021-01-27 11:52:04', '_self', '_self'),
(97, '5cf0ee3445e19363600419.png', 'Vous êtes Investisseur ?', '<ul>\r\n	<li>Parcourez, filtrez et suivez les projets s&eacute;lectionn&eacute;s par notre &eacute;quipe d&rsquo;experts.</li>\r\n	<li>Un projet vous int&eacute;resse ? Contactez-nous pour obtenir plus d&rsquo;information sur l&rsquo;entreprise et l&rsquo;&eacute;quipe dirigeante.</li>\r\n	<li>&eacute;valuation, expertise technique et conseil juridique: notre &eacute;quipe vous accompagne de bout en bout.</li>\r\n</ul>', 'Découvrir les projets', '/fr/projects', 'En savoir plus ?', '/fr/pages/comment-ca-marche/investisseurs', 'fr', '#2C3E50', 'investor', '2021-01-20 08:35:52', '_self', '_self'),
(98, '5cf0ee659de8c340717518.png', 'Investor', '<ul>\r\n	<li>Browse, list&nbsp;and follow projects hand-picked&nbsp;by our team of experts.</li>\r\n	<li>Make direct contact&nbsp;with Founders, and request more information about the Startups</li>\r\n	<li>Due diligence, tax &amp;&nbsp;legal advisory, ...&nbsp;our team is here to provide decision-making insights</li>\r\n</ul>', 'Browse projects', '/en/projects', 'Learn more', '/en/pages/1087-comment-ca-marche-investisseurs', 'en', '#2C3E50', 'investor', '2021-01-27 11:52:10', '_blank', '_blank');

INSERT INTO `background_slider` (`id`, `banner_mobile`, `banner_desktop`, `language`, `created_at`, `updated_at`, `title`) VALUES
(1, '5d63e7e3ce3ce215356181.png', '5cf0eef25678c974842402.png', 'fr', '2021-01-26 17:11:33', '2021-01-20 15:15:14', 'version français'),
(2, '5d63e7e3ce3ce215356181.png', '5cf0eef25678c974842402.png', 'en', '2021-01-26 17:12:07', '2021-01-26 17:12:07', 'english version');

INSERT INTO `slider` (`id`, `title`, `image_name`, `content`, `created_at`, `updated_at`, `lang`, `image_mobile_name`, `button`, `color_text`) VALUES
(1, 'Plateforme de mise en relation entre entrepreneurs et investisseurs', '5d63e7e3ce3ce215356181.png', '<p>Une id&eacute;e. Une innovation. Un projet en developpement.<br />\r\nMettez-le en avant et attirez des Investisseurs.<br />\r\nc&#39;est gratuit et facile &agrave; utiliser.</p>', '2021-01-09 12:29:24', '2021-01-28 15:34:04', 'fr', '5cf0eef25678c974842402.png', '<p><a class=\"btn btn-bg-red btn-h50 btn-w15\" href=\"http://pfestartup.com.com/startuper/project/create\">Soumettre votre projet</a></p>', 'text-black'),
(3, 'Smart platform for connecting founders and investors', '5d63e7e3ce3ce215356181.png', '<p>For Startups. For developping entreprises. For <strong>Business</strong>.<br />\r\nSubmit any project&nbsp;and attract Investors.<br />\r\nIt&#39;s free and easy to use</p>', '2021-01-09 12:32:36', '2021-01-27 11:28:20', 'en', '5cf0eef25678c974842402.png', '<p><span class=\"btn btn-bg-red btn-h50 btn-w15\"><a href=\"http://pfestartup.com.com/startuper/project/create\">Submit a project</a></span></p>', NULL),
(4, 'Find the best investment opportunities', '5d63e7e3ce3ce215356181.png', '<p>Top-up your <strong>dealflow</strong>&nbsp;with verified projects. Contact founders. Request due diligence.</p>\r\n\r\n<p>All-in-one tool for advised investors.</p>', '2021-01-09 12:29:24', '2021-01-05 14:32:45', 'en', '5cf0eef25678c974842402.png', '<p><a class=\"btn btn-bg-red btn-h50 btn-w15\" href=\"http://pfestartup.com.com/en/projects\">Browse projects</a></p>', 'text-black'),
(7, 'Accédez à un Deal Flow qualifié', '5d63e7e3ce3ce215356181.png', '<p>Effectuez des recherches multicrit&egrave;res. Contactez directement les porteurs de projets et investissez dans votre prochaine p&eacute;pite.</p>', '2021-01-20 11:39:27', '2021-01-28 15:33:53', 'fr', '5cf0eef25678c974842402.png', '<p><a class=\"btn btn-bg-red btn-h50 btn-w15\" href=\"http://pfestartup.com.com/fr/pages/comment-ca-marche/investisseurs\">En savoir plus</a></p>', 'text-black'),
(8, 'Feature project : Caftany', '5d63e7e3ce3ce215356181.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eu lectus vel<br />\r\nnibh commodo gravida eu et arcu. Nam pharetra sapien sit amet felis<br />\r\nsuscipit, vel commodo metus volutpat.&nbsp;</p>', '2021-01-29 15:35:05', '2021-01-29 15:41:19', 'fr', '5cf0eef25678c974842402.png', '<p><a class=\"btn btn-bg-red btn-h50 btn-w15\" href=\"#\">Ceci est un bouton</a></p>', 'text-black');


INSERT INTO `garanties_block` (`id`, `title`, `introduction`, `img`, `content`, `lang`, `updated_at`, `slug`) VALUES
(35, 'Our Pledge', 'PFE Startup is first and foremost a strict charter and exchanges  moderated by a team of professionals', '5ce6c61ce82c2051131850.png', '<h3>Intellectual property</h3>\r\n\r\n<p>All information concerning published projects remains the property of the project owners / founders. The acceptance of this charter is mandatory for any user.</p>\r\n\r\n<h3>Confidentiality of exchanges</h3>\r\n\r\n<p>All messages exchanged between founders and investors are strictly confidential and are protected by valid&nbsp;security protocols.</p>\r\n\r\n<p><span class=\"btn btn-h50 btn-transparent-red btn-w15\"><a href=\"http://flowingodemo.egiodigital.com/en/pages/cgu\">Read the charter</a></span></p>\r\n\r\n<h3>Custom support</h3>\r\n\r\n<p>Our team is available to ensure an ergonomic and efficient experience for every user.</p>', 'en', '2021-01-27 12:25:40', 'home'),
(36, 'Nos garanties', 'PFE Startup, c\'est d\'abord une charte stricte et des échanges modérés par une équipe de professionnels', '5ce2785ccfc29440235695.png', '<h3>Respect de la propri&eacute;t&eacute; intellectuelle</h3>\r\n\r\n<p>Toutes les informations concernant les projets publi&eacute;s&nbsp;restent la propri&eacute;t&eacute; des porteurs de projets. L&#39;acceptation de cette charte est obligatoire pour tout utilisateur.&nbsp;</p>\r\n\r\n<h3>Confidentialit&eacute; des &eacute;changes</h3>\r\n\r\n<p>Les messages transmis entre entrepreneurs et invetisseurs sont strictements confidentiels et sont prot&eacute;g&eacute;s par des protocoles de s&eacute;curit&eacute; valides.</p>\r\n\r\n<p><span class=\"btn btn-h50 btn-transparent-red btn-w15\"><a href=\"/fr/pages/about-us?block=confidentialites\">Lire l&#39;engagement&nbsp;CRPI</a></span></p>\r\n\r\n<h3>Un support personalis&eacute;</h3>\r\n\r\n<p>Notre &eacute;quipe est disposnible pour pour garantir une experience ergonomique et efficiace &agrave; chaque utilisateur.</p>\r\n\r\n<h3>&nbsp;</h3>', 'fr', '2021-01-27 12:25:08', 'home');