# config/routes/sonata_admin.yaml

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /boadmin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /boadmin