<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210530010453 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE contributor (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_anonymous TINYINT(1) NOT NULL, email VARCHAR(255) NOT NULL, contribution_amount INT NOT NULL, chosen_payment VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, status VARCHAR(100) DEFAULT NULL, INDEX IDX_DA6F9793979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_finance (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, detail VARCHAR(255) NOT NULL, INDEX IDX_5836E685166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE background_slider (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, language VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintenance (id INT AUTO_INCREMENT NOT NULL, is_locked TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, paragraph LONGTEXT DEFAULT NULL, ttl DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE business_model (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE step (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, help_fr VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, help_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, project_id INT DEFAULT NULL, object VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, seen TINYINT(1) NOT NULL, INDEX IDX_B6BD307FF675F31B (author_id), INDEX IDX_B6BD307F166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reassurance (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, paragraph VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_document (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_C0FE9F1B979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE global_document (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, date DATE NOT NULL, file_name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, type VARCHAR(255) NOT NULL, count_download INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond (id INT AUTO_INCREMENT NOT NULL, fond_type_id INT DEFAULT NULL, gestionnaire_id INT DEFAULT NULL, eligibilite_critere_id INT DEFAULT NULL, depenses_type_id INT DEFAULT NULL, min_id INT DEFAULT NULL, max_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, local VARCHAR(255) NOT NULL, sort_desctiption LONGTEXT NOT NULL, content LONGTEXT NOT NULL, logo VARCHAR(255) DEFAULT NULL, img VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, mail VARCHAR(255) DEFAULT NULL, active TINYINT(1) NOT NULL, amount VARCHAR(255) DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_CD2318B665113B95 (fond_type_id), INDEX IDX_CD2318B66885AC1B (gestionnaire_id), INDEX IDX_CD2318B6261D9F28 (eligibilite_critere_id), INDEX IDX_CD2318B65A4A272 (depenses_type_id), INDEX IDX_CD2318B6D3733409 (min_id), INDEX IDX_CD2318B69671778B (max_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_gestionnaire (fond_id INT NOT NULL, gestionnaire_id INT NOT NULL, INDEX IDX_31C099A987EEAE74 (fond_id), INDEX IDX_31C099A96885AC1B (gestionnaire_id), PRIMARY KEY(fond_id, gestionnaire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_secteur (fond_id INT NOT NULL, secteur_id INT NOT NULL, INDEX IDX_2018921987EEAE74 (fond_id), INDEX IDX_201892199F7E4405 (secteur_id), PRIMARY KEY(fond_id, secteur_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_phase (fond_id INT NOT NULL, phase_id INT NOT NULL, INDEX IDX_8C7613BF87EEAE74 (fond_id), INDEX IDX_8C7613BF99091188 (phase_id), PRIMARY KEY(fond_id, phase_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_financement_type (fond_id INT NOT NULL, financement_type_id INT NOT NULL, INDEX IDX_846CFB1287EEAE74 (fond_id), INDEX IDX_846CFB12FB6CE65B (financement_type_id), PRIMARY KEY(fond_id, financement_type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_depenses_type (fond_id INT NOT NULL, depenses_type_id INT NOT NULL, INDEX IDX_D91DCDD487EEAE74 (fond_id), INDEX IDX_D91DCDD45A4A272 (depenses_type_id), PRIMARY KEY(fond_id, depenses_type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_comment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, company_id INT DEFAULT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, is_published TINYINT(1) NOT NULL, INDEX IDX_B42648BBF675F31B (author_id), INDEX IDX_B42648BB979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE financement_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_like (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_EF0E5A5D979B1AD6 (company_id), INDEX IDX_EF0E5A5DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_type (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reassurance_col (id INT AUTO_INCREMENT NOT NULL, reassurance_id INT DEFAULT NULL, col VARCHAR(255) DEFAULT NULL, img_name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3FD76AFE3B62EE (reassurance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_response (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, user_id INT DEFAULT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, seen TINYINT(1) NOT NULL, INDEX IDX_375DCFEA537A1329 (message_id), INDEX IDX_375DCFEAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE slider (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_mobile_name VARCHAR(255) DEFAULT NULL, color_text VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, button LONGTEXT DEFAULT NULL, lang VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE log_download (id INT AUTO_INCREMENT NOT NULL, document_id INT DEFAULT NULL, tool_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, downloaded_at DATETIME NOT NULL, INDEX IDX_164949AFC33F7837 (document_id), INDEX IDX_164949AF8F7B22CC (tool_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, role_id INT NOT NULL, city_id INT DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, birthday DATE DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, profile VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, is_active TINYINT(1) NOT NULL, token VARCHAR(255) DEFAULT NULL, date_token DATETIME DEFAULT NULL, is_banned TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, social_reason VARCHAR(255) DEFAULT NULL, INDEX IDX_8D93D649D60322AC (role_id), INDEX IDX_8D93D6498BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_avantage (id INT AUTO_INCREMENT NOT NULL, approved_project_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_9578E689B14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fond_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_channels (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sector (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_gallery_photo (id INT AUTO_INCREMENT NOT NULL, approved_project_id INT NOT NULL, name VARCHAR(255) NOT NULL, alt VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_C10AEA9EB14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE depenses_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_use_fund (id INT AUTO_INCREMENT NOT NULL, approved_company_id INT NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_7F9B3AB830B804BF (approved_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE montant (id INT AUTO_INCREMENT NOT NULL, montant_min VARCHAR(255) NOT NULL, montant_max VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_document (id INT AUTO_INCREMENT NOT NULL, document_type_id INT DEFAULT NULL, approved_project_id INT NOT NULL, name VARCHAR(255) NOT NULL, is_private TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E44C1D1A61232A4F (document_type_id), INDEX IDX_E44C1D1AB14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_member (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, photo VARCHAR(255) DEFAULT NULL, position VARCHAR(255) NOT NULL, porteur TINYINT(1) NOT NULL, biography LONGTEXT DEFAULT NULL, cv VARCHAR(255) DEFAULT NULL, linkedin VARCHAR(255) DEFAULT NULL, twitter VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_6FFBDA1166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_company (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, text LONGTEXT NOT NULL, association_name VARCHAR(255) NOT NULL, duration INT NOT NULL, funding_objective DOUBLE PRECISION NOT NULL, rib VARCHAR(255) NOT NULL, logo_name VARCHAR(255) DEFAULT NULL, cover_name VARCHAR(255) DEFAULT NULL, web_site VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, slug VARCHAR(255) NOT NULL, is_verified TINYINT(1) NOT NULL, is_approved TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_69CCB46B979B1AD6 (company_id), INDEX IDX_69CCB46BA76ED395 (user_id), INDEX IDX_69CCB46B8BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_company_domain (approved_company_id INT NOT NULL, domain_id INT NOT NULL, INDEX IDX_3CBB0DA730B804BF (approved_company_id), INDEX IDX_3CBB0DA7115F0EE5 (domain_id), PRIMARY KEY(approved_company_id, domain_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE secteur (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_project (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, step_id INT DEFAULT NULL, earned_id INT NOT NULL, author_id INT NOT NULL, language VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, startup TINYINT(1) NOT NULL, denomination VARCHAR(255) DEFAULT NULL, creating_date DATE DEFAULT NULL, rc VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, other_sales_channels TINYINT(1) DEFAULT NULL, more_sales_channels VARCHAR(255) DEFAULT NULL, more_sectors VARCHAR(255) DEFAULT NULL, other_business_model TINYINT(1) DEFAULT NULL, more_business_model VARCHAR(255) DEFAULT NULL, morocco TINYINT(1) DEFAULT NULL, other_country TINYINT(1) DEFAULT NULL, foreign_country VARCHAR(255) DEFAULT NULL, market_research TINYINT(1) DEFAULT NULL, budget INT DEFAULT NULL, raised INT DEFAULT NULL, has_not_amount TINYINT(1) DEFAULT NULL, amount INT DEFAULT NULL, summary LONGTEXT DEFAULT NULL, express LONGTEXT DEFAULT NULL, video VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, image_cover_name VARCHAR(255) DEFAULT NULL, logo_name VARCHAR(255) DEFAULT NULL, is_verified TINYINT(1) NOT NULL, is_approved TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, order_by INT DEFAULT NULL, UNIQUE INDEX UNIQ_9C06DCA166D1F9C (project_id), INDEX IDX_9C06DCA73B21E9C (step_id), INDEX IDX_9C06DCAD9235B03 (earned_id), INDEX IDX_9C06DCAF675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_project_sales_channels (approved_project_id INT NOT NULL, sales_channels_id INT NOT NULL, INDEX IDX_3ACBA092B14E01F5 (approved_project_id), INDEX IDX_3ACBA092950B13B6 (sales_channels_id), PRIMARY KEY(approved_project_id, sales_channels_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_project_sector (approved_project_id INT NOT NULL, sector_id INT NOT NULL, INDEX IDX_FA8A457BB14E01F5 (approved_project_id), INDEX IDX_FA8A457BDE95C867 (sector_id), PRIMARY KEY(approved_project_id, sector_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_project_business_model (approved_project_id INT NOT NULL, business_model_id INT NOT NULL, INDEX IDX_2D174F66B14E01F5 (approved_project_id), INDEX IDX_2D174F667145B971 (business_model_id), PRIMARY KEY(approved_project_id, business_model_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project (id INT AUTO_INCREMENT NOT NULL, step_id INT DEFAULT NULL, earned_id INT DEFAULT NULL, author_id INT NOT NULL, language VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, summary LONGTEXT DEFAULT NULL, startup TINYINT(1) NOT NULL, denomination VARCHAR(255) DEFAULT NULL, creating_date DATE DEFAULT NULL, rc VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, other_sales_channels TINYINT(1) DEFAULT NULL, more_sales_channels VARCHAR(255) DEFAULT NULL, more_sectors VARCHAR(255) DEFAULT NULL, other_business_model TINYINT(1) DEFAULT NULL, more_business_model VARCHAR(255) DEFAULT NULL, morocco TINYINT(1) DEFAULT NULL, other_country TINYINT(1) DEFAULT NULL, foreign_country VARCHAR(255) DEFAULT NULL, market_research TINYINT(1) DEFAULT NULL, budget INT DEFAULT NULL, raised INT DEFAULT NULL, amount INT DEFAULT NULL, express LONGTEXT DEFAULT NULL, video VARCHAR(255) DEFAULT NULL, step_creating INT NOT NULL, step_updating INT NOT NULL, is_draft TINYINT(1) NOT NULL, is_verified TINYINT(1) NOT NULL, is_approved TINYINT(1) NOT NULL, is_rejected TINYINT(1) NOT NULL, is_updated TINYINT(1) NOT NULL, is_locked TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, slug VARCHAR(255) NOT NULL, image_cover_name VARCHAR(255) DEFAULT NULL, logo_name VARCHAR(255) DEFAULT NULL, views INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, prints INT DEFAULT NULL, has_not_amount TINYINT(1) DEFAULT NULL, order_by INT DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, INDEX IDX_2FB3D0EE73B21E9C (step_id), INDEX IDX_2FB3D0EED9235B03 (earned_id), INDEX IDX_2FB3D0EEF675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_sales_channels (project_id INT NOT NULL, sales_channels_id INT NOT NULL, INDEX IDX_571F4E30166D1F9C (project_id), INDEX IDX_571F4E30950B13B6 (sales_channels_id), PRIMARY KEY(project_id, sales_channels_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_sector (project_id INT NOT NULL, sector_id INT NOT NULL, INDEX IDX_5C0732A2166D1F9C (project_id), INDEX IDX_5C0732A2DE95C867 (sector_id), PRIMARY KEY(project_id, sector_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_business_model (project_id INT NOT NULL, business_model_id INT NOT NULL, INDEX IDX_40C3A1C4166D1F9C (project_id), INDEX IDX_40C3A1C47145B971 (business_model_id), PRIMARY KEY(project_id, business_model_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE eligibilite_critere (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, language VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE request_documentation (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, project_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, is_accepted TINYINT(1) DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, accepted_at DATETIME DEFAULT NULL, INDEX IDX_FBC6D984A76ED395 (user_id), INDEX IDX_FBC6D984166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE request_documentation_document_type (request_documentation_id INT NOT NULL, document_type_id INT NOT NULL, INDEX IDX_25EB7E3BA2806F44 (request_documentation_id), INDEX IDX_25EB7E3B61232A4F (document_type_id), PRIMARY KEY(request_documentation_id, document_type_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_info (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, info VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garanties_block (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, introduction VARCHAR(255) NOT NULL, img VARCHAR(255) DEFAULT NULL, content LONGTEXT NOT NULL, lang VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, object VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE use_fund (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_43BEADD4979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE earned (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, label_en VARCHAR(255) DEFAULT NULL, show_in_front TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_comment_response (id INT AUTO_INCREMENT NOT NULL, comment_id INT DEFAULT NULL, user_id INT DEFAULT NULL, content LONGTEXT NOT NULL, created_at DATETIME NOT NULL, is_published TINYINT(1) NOT NULL, INDEX IDX_DC49446F8697D13 (comment_id), INDEX IDX_DC49446A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_company_document (id INT AUTO_INCREMENT NOT NULL, approved_company_id INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_5E65A35F30B804BF (approved_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gestionnaire (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_like (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_95F288AB166D1F9C (project_id), INDEX IDX_95F288ABA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, document_type_id INT DEFAULT NULL, project_id INT NOT NULL, name VARCHAR(255) NOT NULL, is_private TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D8698A7661232A4F (document_type_id), INDEX IDX_D8698A76166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_project_finance (id INT AUTO_INCREMENT NOT NULL, approved_project_id INT NOT NULL, detail VARCHAR(255) NOT NULL, INDEX IDX_A79F0182B14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, city_id INT DEFAULT NULL, approved_company_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, text LONGTEXT NOT NULL, association_name VARCHAR(255) NOT NULL, duration INT NOT NULL, funding_objective DOUBLE PRECISION NOT NULL, rib VARCHAR(255) NOT NULL, logo_name VARCHAR(255) DEFAULT NULL, cover_name VARCHAR(255) DEFAULT NULL, web_site VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, slug VARCHAR(255) NOT NULL, is_legal_representative_of_the_association TINYINT(1) NOT NULL, is_accepted_the_condition_of_security TINYINT(1) NOT NULL, is_draft TINYINT(1) NOT NULL, is_verified TINYINT(1) NOT NULL, is_approved TINYINT(1) NOT NULL, is_rejected TINYINT(1) NOT NULL, is_updated TINYINT(1) NOT NULL, is_locked TINYINT(1) NOT NULL, is_deleted TINYINT(1) NOT NULL, views INT DEFAULT NULL, prints INT DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, start_date DATETIME DEFAULT NULL, end_date DATETIME DEFAULT NULL, INDEX IDX_4FBF094FA76ED395 (user_id), INDEX IDX_4FBF094F8BAC62AF (city_id), UNIQUE INDEX UNIQ_4FBF094F30B804BF (approved_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_domain (company_id INT NOT NULL, domain_id INT NOT NULL, INDEX IDX_9A367A7E979B1AD6 (company_id), INDEX IDX_9A367A7E115F0EE5 (domain_id), PRIMARY KEY(company_id, domain_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mail_sended (id INT AUTO_INCREMENT NOT NULL, project_id INT DEFAULT NULL, user_id INT DEFAULT NULL, mail VARCHAR(255) NOT NULL, date DATETIME DEFAULT NULL, wich_mail INT NOT NULL, INDEX IDX_76ED40F5166D1F9C (project_id), INDEX IDX_76ED40F5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE email_template (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, language VARCHAR(255) NOT NULL, label VARCHAR(255) DEFAULT NULL, template VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE testimonial (id INT AUTO_INCREMENT NOT NULL, full_name VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, avatar VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_team_member (id INT AUTO_INCREMENT NOT NULL, approved_project_id INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, photo VARCHAR(255) DEFAULT NULL, position VARCHAR(255) NOT NULL, biography LONGTEXT DEFAULT NULL, linkedin VARCHAR(255) DEFAULT NULL, twitter VARCHAR(255) DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, cv VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, porteur TINYINT(1) NOT NULL, INDEX IDX_32364743B14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE domain (id INT AUTO_INCREMENT NOT NULL, label_fr VARCHAR(255) NOT NULL, label_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_E19D9AD2166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE header (id INT AUTO_INCREMENT NOT NULL, banner_name VARCHAR(255) DEFAULT NULL, description LONGTEXT NOT NULL, page VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment_ca_marche_block (id INT AUTO_INCREMENT NOT NULL, img VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, btn1text VARCHAR(255) NOT NULL, btn1link VARCHAR(255) NOT NULL, btn1target VARCHAR(255) NOT NULL, btn2text VARCHAR(255) DEFAULT NULL, btn2link VARCHAR(255) DEFAULT NULL, btn2target VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) NOT NULL, background_color VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_photo (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, name VARCHAR(255) NOT NULL, alt VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_F02A543B166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE avantage (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, name LONGTEXT NOT NULL, INDEX IDX_A95D71E5166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE approved_service (id INT AUTO_INCREMENT NOT NULL, approved_project_id INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_C7EE27F6B14E01F5 (approved_project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, project_id INT DEFAULT NULL, question LONGTEXT NOT NULL, response LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, seen TINYINT(1) NOT NULL, INDEX IDX_E8FF75CCF675F31B (author_id), INDEX IDX_E8FF75CC166D1F9C (project_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE phase (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE funding_objective (id INT AUTO_INCREMENT NOT NULL, min INT DEFAULT NULL, max INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE request_doc_accepted (id INT AUTO_INCREMENT NOT NULL, request_id INT DEFAULT NULL, type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_C83B2CD427EB8A5 (request_id), INDEX IDX_C83B2CDC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tools (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, file_name VARCHAR(255) NOT NULL, icon VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, count_download INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_faq (id INT AUTO_INCREMENT NOT NULL, question VARCHAR(255) NOT NULL, response LONGTEXT NOT NULL, language VARCHAR(255) NOT NULL, is_published TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ip (id INT AUTO_INCREMENT NOT NULL, maintenance_id INT NOT NULL, ip VARCHAR(255) NOT NULL, INDEX IDX_A5E3B32DF6C202BC (maintenance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block_published (id INT AUTO_INCREMENT NOT NULL, page_id INT DEFAULT NULL, article_id INT DEFAULT NULL, event_id INT DEFAULT NULL, col_large INT NOT NULL, clearfix TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, title VARCHAR(255) DEFAULT NULL, link_video VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, text_image LONGTEXT DEFAULT NULL, legend VARCHAR(255) DEFAULT NULL, link_image VARCHAR(255) DEFAULT NULL, position INT UNSIGNED DEFAULT 0 NOT NULL, type LONGTEXT DEFAULT NULL, width INT NOT NULL, height INT NOT NULL, `row` INT UNSIGNED DEFAULT 0 NOT NULL, INDEX IDX_58D3E002C4663E4 (page_id), INDEX IDX_58D3E0027294869C (article_id), INDEX IDX_58D3E00271F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_published (id INT AUTO_INCREMENT NOT NULL, page_id INT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_tags VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_page_simple TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, content_banner LONGTEXT DEFAULT NULL, lang VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_53D2DFD8C4663E4 (page_id), INDEX IDX_53D2DFD812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_tags VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, count_views INT NOT NULL, is_active TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, date_tri DATE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_23A0E6612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_like (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_B3A80C1871F7E88B (event_id), INDEX IDX_B3A80C18A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, meta_title VARCHAR(255) NOT NULL, meta_tags VARCHAR(255) NOT NULL, meta_description VARCHAR(255) NOT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_page_simple TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, content_banner LONGTEXT DEFAULT NULL, lang VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_140AB62012469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_event (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_published (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, event_id INT NOT NULL, title VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, lieu VARCHAR(255) NOT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, heure_debut TIME DEFAULT NULL, heure_fin TIME DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_tags VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, count_views INT NOT NULL, is_active TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_EEA95E2A12469DE2 (category_id), UNIQUE INDEX UNIQ_EEA95E2A71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_like (id INT AUTO_INCREMENT NOT NULL, article_id INT NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_1C21C7B27294869C (article_id), INDEX IDX_1C21C7B2A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_view (id INT AUTO_INCREMENT NOT NULL, article_id INT NOT NULL, ip VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_4EBF2C8F7294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_article (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_view (id INT AUTO_INCREMENT NOT NULL, event_id INT NOT NULL, ip VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_E136E72571F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_page (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE row_published (id INT AUTO_INCREMENT NOT NULL, index_row INT DEFAULT NULL, id_cms INT DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, id_html VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_published (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, article_id INT NOT NULL, title VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_tags VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, count_views INT NOT NULL, is_active TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, date_tri DATE NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B209303312469DE2 (category_id), UNIQUE INDEX UNIQ_B20930337294869C (article_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE block (id INT AUTO_INCREMENT NOT NULL, page_id INT DEFAULT NULL, article_id INT DEFAULT NULL, event_id INT DEFAULT NULL, col_large INT NOT NULL, clearfix TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, title VARCHAR(255) DEFAULT NULL, link_video VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, text_image LONGTEXT DEFAULT NULL, legend VARCHAR(255) DEFAULT NULL, link_image VARCHAR(255) DEFAULT NULL, position INT UNSIGNED DEFAULT 0 NOT NULL, type LONGTEXT DEFAULT NULL, width INT NOT NULL, height INT NOT NULL, `row` INT UNSIGNED DEFAULT 0 NOT NULL, INDEX IDX_831B9722C4663E4 (page_id), INDEX IDX_831B97227294869C (article_id), INDEX IDX_831B972271F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, lang VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, lieu VARCHAR(255) NOT NULL, date_debut DATETIME DEFAULT NULL, date_fin DATETIME DEFAULT NULL, heure_debut TIME DEFAULT NULL, heure_fin TIME DEFAULT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_tags VARCHAR(255) DEFAULT NULL, meta_description VARCHAR(255) DEFAULT NULL, html_id_attr VARCHAR(255) DEFAULT NULL, html_class_attr VARCHAR(255) DEFAULT NULL, content LONGTEXT DEFAULT NULL, count_views INT NOT NULL, is_active TINYINT(1) NOT NULL, is_expired TINYINT(1) NOT NULL, banner_desktop VARCHAR(255) DEFAULT NULL, banner_mobile VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3BAE0AA712469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `row` (id INT AUTO_INCREMENT NOT NULL, index_row INT DEFAULT NULL, id_cms INT DEFAULT NULL, class VARCHAR(255) DEFAULT NULL, id_html VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE offer_request (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, block VARCHAR(255) DEFAULT NULL, message LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE contributor ADD CONSTRAINT FK_DA6F9793979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE project_finance ADD CONSTRAINT FK_5836E685166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_document ADD CONSTRAINT FK_C0FE9F1B979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B665113B95 FOREIGN KEY (fond_type_id) REFERENCES fond_type (id)');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B66885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES gestionnaire (id)');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B6261D9F28 FOREIGN KEY (eligibilite_critere_id) REFERENCES eligibilite_critere (id)');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B65A4A272 FOREIGN KEY (depenses_type_id) REFERENCES depenses_type (id)');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B6D3733409 FOREIGN KEY (min_id) REFERENCES montant (id)');
        $this->addSql('ALTER TABLE fond ADD CONSTRAINT FK_CD2318B69671778B FOREIGN KEY (max_id) REFERENCES montant (id)');
        $this->addSql('ALTER TABLE fond_gestionnaire ADD CONSTRAINT FK_31C099A987EEAE74 FOREIGN KEY (fond_id) REFERENCES fond (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_gestionnaire ADD CONSTRAINT FK_31C099A96885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES gestionnaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_secteur ADD CONSTRAINT FK_2018921987EEAE74 FOREIGN KEY (fond_id) REFERENCES fond (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_secteur ADD CONSTRAINT FK_201892199F7E4405 FOREIGN KEY (secteur_id) REFERENCES secteur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_phase ADD CONSTRAINT FK_8C7613BF87EEAE74 FOREIGN KEY (fond_id) REFERENCES fond (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_phase ADD CONSTRAINT FK_8C7613BF99091188 FOREIGN KEY (phase_id) REFERENCES phase (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_financement_type ADD CONSTRAINT FK_846CFB1287EEAE74 FOREIGN KEY (fond_id) REFERENCES fond (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_financement_type ADD CONSTRAINT FK_846CFB12FB6CE65B FOREIGN KEY (financement_type_id) REFERENCES financement_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_depenses_type ADD CONSTRAINT FK_D91DCDD487EEAE74 FOREIGN KEY (fond_id) REFERENCES fond (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fond_depenses_type ADD CONSTRAINT FK_D91DCDD45A4A272 FOREIGN KEY (depenses_type_id) REFERENCES depenses_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_comment ADD CONSTRAINT FK_B42648BBF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company_comment ADD CONSTRAINT FK_B42648BB979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_like ADD CONSTRAINT FK_EF0E5A5D979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_like ADD CONSTRAINT FK_EF0E5A5DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE reassurance_col ADD CONSTRAINT FK_3FD76AFE3B62EE FOREIGN KEY (reassurance_id) REFERENCES reassurance (id)');
        $this->addSql('ALTER TABLE message_response ADD CONSTRAINT FK_375DCFEA537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_response ADD CONSTRAINT FK_375DCFEAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE log_download ADD CONSTRAINT FK_164949AFC33F7837 FOREIGN KEY (document_id) REFERENCES global_document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE log_download ADD CONSTRAINT FK_164949AF8F7B22CC FOREIGN KEY (tool_id) REFERENCES tools (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES role (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6498BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE approved_avantage ADD CONSTRAINT FK_9578E689B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_gallery_photo ADD CONSTRAINT FK_C10AEA9EB14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_use_fund ADD CONSTRAINT FK_7F9B3AB830B804BF FOREIGN KEY (approved_company_id) REFERENCES approved_company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_document ADD CONSTRAINT FK_E44C1D1A61232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE approved_document ADD CONSTRAINT FK_E44C1D1AB14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_member ADD CONSTRAINT FK_6FFBDA1166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_company ADD CONSTRAINT FK_69CCB46B979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_company ADD CONSTRAINT FK_69CCB46BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE approved_company ADD CONSTRAINT FK_69CCB46B8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE approved_company_domain ADD CONSTRAINT FK_3CBB0DA730B804BF FOREIGN KEY (approved_company_id) REFERENCES approved_company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_company_domain ADD CONSTRAINT FK_3CBB0DA7115F0EE5 FOREIGN KEY (domain_id) REFERENCES domain (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project ADD CONSTRAINT FK_9C06DCA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project ADD CONSTRAINT FK_9C06DCA73B21E9C FOREIGN KEY (step_id) REFERENCES step (id)');
        $this->addSql('ALTER TABLE approved_project ADD CONSTRAINT FK_9C06DCAD9235B03 FOREIGN KEY (earned_id) REFERENCES earned (id)');
        $this->addSql('ALTER TABLE approved_project ADD CONSTRAINT FK_9C06DCAF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE approved_project_sales_channels ADD CONSTRAINT FK_3ACBA092B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_sales_channels ADD CONSTRAINT FK_3ACBA092950B13B6 FOREIGN KEY (sales_channels_id) REFERENCES sales_channels (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_sector ADD CONSTRAINT FK_FA8A457BB14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_sector ADD CONSTRAINT FK_FA8A457BDE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_business_model ADD CONSTRAINT FK_2D174F66B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_business_model ADD CONSTRAINT FK_2D174F667145B971 FOREIGN KEY (business_model_id) REFERENCES business_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE73B21E9C FOREIGN KEY (step_id) REFERENCES step (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EED9235B03 FOREIGN KEY (earned_id) REFERENCES earned (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE project_sales_channels ADD CONSTRAINT FK_571F4E30166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_sales_channels ADD CONSTRAINT FK_571F4E30950B13B6 FOREIGN KEY (sales_channels_id) REFERENCES sales_channels (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_sector ADD CONSTRAINT FK_5C0732A2166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_sector ADD CONSTRAINT FK_5C0732A2DE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_business_model ADD CONSTRAINT FK_40C3A1C4166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_business_model ADD CONSTRAINT FK_40C3A1C47145B971 FOREIGN KEY (business_model_id) REFERENCES business_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_documentation ADD CONSTRAINT FK_FBC6D984A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE request_documentation ADD CONSTRAINT FK_FBC6D984166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_documentation_document_type ADD CONSTRAINT FK_25EB7E3BA2806F44 FOREIGN KEY (request_documentation_id) REFERENCES request_documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_documentation_document_type ADD CONSTRAINT FK_25EB7E3B61232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE use_fund ADD CONSTRAINT FK_43BEADD4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_comment_response ADD CONSTRAINT FK_DC49446F8697D13 FOREIGN KEY (comment_id) REFERENCES company_comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_comment_response ADD CONSTRAINT FK_DC49446A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE approved_company_document ADD CONSTRAINT FK_5E65A35F30B804BF FOREIGN KEY (approved_company_id) REFERENCES approved_company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_like ADD CONSTRAINT FK_95F288AB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project_like ADD CONSTRAINT FK_95F288ABA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7661232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_project_finance ADD CONSTRAINT FK_A79F0182B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F30B804BF FOREIGN KEY (approved_company_id) REFERENCES approved_company (id)');
        $this->addSql('ALTER TABLE company_domain ADD CONSTRAINT FK_9A367A7E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_domain ADD CONSTRAINT FK_9A367A7E115F0EE5 FOREIGN KEY (domain_id) REFERENCES domain (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mail_sended ADD CONSTRAINT FK_76ED40F5166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mail_sended ADD CONSTRAINT FK_76ED40F5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_team_member ADD CONSTRAINT FK_32364743B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_photo ADD CONSTRAINT FK_F02A543B166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE avantage ADD CONSTRAINT FK_A95D71E5166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE approved_service ADD CONSTRAINT FK_C7EE27F6B14E01F5 FOREIGN KEY (approved_project_id) REFERENCES approved_project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE faq ADD CONSTRAINT FK_E8FF75CCF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE faq ADD CONSTRAINT FK_E8FF75CC166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_doc_accepted ADD CONSTRAINT FK_C83B2CD427EB8A5 FOREIGN KEY (request_id) REFERENCES request_documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE request_doc_accepted ADD CONSTRAINT FK_C83B2CDC54C8C93 FOREIGN KEY (type_id) REFERENCES document_type (id)');
        $this->addSql('ALTER TABLE ip ADD CONSTRAINT FK_A5E3B32DF6C202BC FOREIGN KEY (maintenance_id) REFERENCES maintenance (id)');
        $this->addSql('ALTER TABLE block_published ADD CONSTRAINT FK_58D3E002C4663E4 FOREIGN KEY (page_id) REFERENCES page_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_published ADD CONSTRAINT FK_58D3E0027294869C FOREIGN KEY (article_id) REFERENCES article_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block_published ADD CONSTRAINT FK_58D3E00271F7E88B FOREIGN KEY (event_id) REFERENCES event_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE page_published ADD CONSTRAINT FK_53D2DFD8C4663E4 FOREIGN KEY (page_id) REFERENCES page (id)');
        $this->addSql('ALTER TABLE page_published ADD CONSTRAINT FK_53D2DFD812469DE2 FOREIGN KEY (category_id) REFERENCES category_page (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES category_article (id)');
        $this->addSql('ALTER TABLE event_like ADD CONSTRAINT FK_B3A80C1871F7E88B FOREIGN KEY (event_id) REFERENCES event_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_like ADD CONSTRAINT FK_B3A80C18A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE page ADD CONSTRAINT FK_140AB62012469DE2 FOREIGN KEY (category_id) REFERENCES category_page (id)');
        $this->addSql('ALTER TABLE event_published ADD CONSTRAINT FK_EEA95E2A12469DE2 FOREIGN KEY (category_id) REFERENCES category_event (id)');
        $this->addSql('ALTER TABLE event_published ADD CONSTRAINT FK_EEA95E2A71F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE article_like ADD CONSTRAINT FK_1C21C7B27294869C FOREIGN KEY (article_id) REFERENCES article_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_like ADD CONSTRAINT FK_1C21C7B2A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article_view ADD CONSTRAINT FK_4EBF2C8F7294869C FOREIGN KEY (article_id) REFERENCES article_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_view ADD CONSTRAINT FK_E136E72571F7E88B FOREIGN KEY (event_id) REFERENCES event_published (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_published ADD CONSTRAINT FK_B209303312469DE2 FOREIGN KEY (category_id) REFERENCES category_article (id)');
        $this->addSql('ALTER TABLE article_published ADD CONSTRAINT FK_B20930337294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE block ADD CONSTRAINT FK_831B9722C4663E4 FOREIGN KEY (page_id) REFERENCES page (id)');
        $this->addSql('ALTER TABLE block ADD CONSTRAINT FK_831B97227294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE block ADD CONSTRAINT FK_831B972271F7E88B FOREIGN KEY (event_id) REFERENCES event (id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA712469DE2 FOREIGN KEY (category_id) REFERENCES category_event (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE ip DROP FOREIGN KEY FK_A5E3B32DF6C202BC');
        $this->addSql('ALTER TABLE approved_project_business_model DROP FOREIGN KEY FK_2D174F667145B971');
        $this->addSql('ALTER TABLE project_business_model DROP FOREIGN KEY FK_40C3A1C47145B971');
        $this->addSql('ALTER TABLE approved_project DROP FOREIGN KEY FK_9C06DCA73B21E9C');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE73B21E9C');
        $this->addSql('ALTER TABLE message_response DROP FOREIGN KEY FK_375DCFEA537A1329');
        $this->addSql('ALTER TABLE reassurance_col DROP FOREIGN KEY FK_3FD76AFE3B62EE');
        $this->addSql('ALTER TABLE log_download DROP FOREIGN KEY FK_164949AFC33F7837');
        $this->addSql('ALTER TABLE fond_gestionnaire DROP FOREIGN KEY FK_31C099A987EEAE74');
        $this->addSql('ALTER TABLE fond_secteur DROP FOREIGN KEY FK_2018921987EEAE74');
        $this->addSql('ALTER TABLE fond_phase DROP FOREIGN KEY FK_8C7613BF87EEAE74');
        $this->addSql('ALTER TABLE fond_financement_type DROP FOREIGN KEY FK_846CFB1287EEAE74');
        $this->addSql('ALTER TABLE fond_depenses_type DROP FOREIGN KEY FK_D91DCDD487EEAE74');
        $this->addSql('ALTER TABLE company_comment_response DROP FOREIGN KEY FK_DC49446F8697D13');
        $this->addSql('ALTER TABLE fond_financement_type DROP FOREIGN KEY FK_846CFB12FB6CE65B');
        $this->addSql('ALTER TABLE approved_document DROP FOREIGN KEY FK_E44C1D1A61232A4F');
        $this->addSql('ALTER TABLE request_documentation_document_type DROP FOREIGN KEY FK_25EB7E3B61232A4F');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7661232A4F');
        $this->addSql('ALTER TABLE request_doc_accepted DROP FOREIGN KEY FK_C83B2CDC54C8C93');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE company_comment DROP FOREIGN KEY FK_B42648BBF675F31B');
        $this->addSql('ALTER TABLE company_like DROP FOREIGN KEY FK_EF0E5A5DA76ED395');
        $this->addSql('ALTER TABLE message_response DROP FOREIGN KEY FK_375DCFEAA76ED395');
        $this->addSql('ALTER TABLE approved_company DROP FOREIGN KEY FK_69CCB46BA76ED395');
        $this->addSql('ALTER TABLE approved_project DROP FOREIGN KEY FK_9C06DCAF675F31B');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EEF675F31B');
        $this->addSql('ALTER TABLE request_documentation DROP FOREIGN KEY FK_FBC6D984A76ED395');
        $this->addSql('ALTER TABLE company_comment_response DROP FOREIGN KEY FK_DC49446A76ED395');
        $this->addSql('ALTER TABLE project_like DROP FOREIGN KEY FK_95F288ABA76ED395');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FA76ED395');
        $this->addSql('ALTER TABLE mail_sended DROP FOREIGN KEY FK_76ED40F5A76ED395');
        $this->addSql('ALTER TABLE faq DROP FOREIGN KEY FK_E8FF75CCF675F31B');
        $this->addSql('ALTER TABLE event_like DROP FOREIGN KEY FK_B3A80C18A76ED395');
        $this->addSql('ALTER TABLE article_like DROP FOREIGN KEY FK_1C21C7B2A76ED395');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B665113B95');
        $this->addSql('ALTER TABLE approved_project_sales_channels DROP FOREIGN KEY FK_3ACBA092950B13B6');
        $this->addSql('ALTER TABLE project_sales_channels DROP FOREIGN KEY FK_571F4E30950B13B6');
        $this->addSql('ALTER TABLE approved_project_sector DROP FOREIGN KEY FK_FA8A457BDE95C867');
        $this->addSql('ALTER TABLE project_sector DROP FOREIGN KEY FK_5C0732A2DE95C867');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B65A4A272');
        $this->addSql('ALTER TABLE fond_depenses_type DROP FOREIGN KEY FK_D91DCDD45A4A272');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B6D3733409');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B69671778B');
        $this->addSql('ALTER TABLE approved_use_fund DROP FOREIGN KEY FK_7F9B3AB830B804BF');
        $this->addSql('ALTER TABLE approved_company_domain DROP FOREIGN KEY FK_3CBB0DA730B804BF');
        $this->addSql('ALTER TABLE approved_company_document DROP FOREIGN KEY FK_5E65A35F30B804BF');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F30B804BF');
        $this->addSql('ALTER TABLE fond_secteur DROP FOREIGN KEY FK_201892199F7E4405');
        $this->addSql('ALTER TABLE approved_avantage DROP FOREIGN KEY FK_9578E689B14E01F5');
        $this->addSql('ALTER TABLE approved_gallery_photo DROP FOREIGN KEY FK_C10AEA9EB14E01F5');
        $this->addSql('ALTER TABLE approved_document DROP FOREIGN KEY FK_E44C1D1AB14E01F5');
        $this->addSql('ALTER TABLE approved_project_sales_channels DROP FOREIGN KEY FK_3ACBA092B14E01F5');
        $this->addSql('ALTER TABLE approved_project_sector DROP FOREIGN KEY FK_FA8A457BB14E01F5');
        $this->addSql('ALTER TABLE approved_project_business_model DROP FOREIGN KEY FK_2D174F66B14E01F5');
        $this->addSql('ALTER TABLE approved_project_finance DROP FOREIGN KEY FK_A79F0182B14E01F5');
        $this->addSql('ALTER TABLE approved_team_member DROP FOREIGN KEY FK_32364743B14E01F5');
        $this->addSql('ALTER TABLE approved_service DROP FOREIGN KEY FK_C7EE27F6B14E01F5');
        $this->addSql('ALTER TABLE project_finance DROP FOREIGN KEY FK_5836E685166D1F9C');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F166D1F9C');
        $this->addSql('ALTER TABLE team_member DROP FOREIGN KEY FK_6FFBDA1166D1F9C');
        $this->addSql('ALTER TABLE approved_project DROP FOREIGN KEY FK_9C06DCA166D1F9C');
        $this->addSql('ALTER TABLE project_sales_channels DROP FOREIGN KEY FK_571F4E30166D1F9C');
        $this->addSql('ALTER TABLE project_sector DROP FOREIGN KEY FK_5C0732A2166D1F9C');
        $this->addSql('ALTER TABLE project_business_model DROP FOREIGN KEY FK_40C3A1C4166D1F9C');
        $this->addSql('ALTER TABLE request_documentation DROP FOREIGN KEY FK_FBC6D984166D1F9C');
        $this->addSql('ALTER TABLE project_like DROP FOREIGN KEY FK_95F288AB166D1F9C');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76166D1F9C');
        $this->addSql('ALTER TABLE mail_sended DROP FOREIGN KEY FK_76ED40F5166D1F9C');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2166D1F9C');
        $this->addSql('ALTER TABLE gallery_photo DROP FOREIGN KEY FK_F02A543B166D1F9C');
        $this->addSql('ALTER TABLE avantage DROP FOREIGN KEY FK_A95D71E5166D1F9C');
        $this->addSql('ALTER TABLE faq DROP FOREIGN KEY FK_E8FF75CC166D1F9C');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B6261D9F28');
        $this->addSql('ALTER TABLE request_documentation_document_type DROP FOREIGN KEY FK_25EB7E3BA2806F44');
        $this->addSql('ALTER TABLE request_doc_accepted DROP FOREIGN KEY FK_C83B2CD427EB8A5');
        $this->addSql('ALTER TABLE approved_project DROP FOREIGN KEY FK_9C06DCAD9235B03');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EED9235B03');
        $this->addSql('ALTER TABLE fond DROP FOREIGN KEY FK_CD2318B66885AC1B');
        $this->addSql('ALTER TABLE fond_gestionnaire DROP FOREIGN KEY FK_31C099A96885AC1B');
        $this->addSql('ALTER TABLE contributor DROP FOREIGN KEY FK_DA6F9793979B1AD6');
        $this->addSql('ALTER TABLE company_document DROP FOREIGN KEY FK_C0FE9F1B979B1AD6');
        $this->addSql('ALTER TABLE company_comment DROP FOREIGN KEY FK_B42648BB979B1AD6');
        $this->addSql('ALTER TABLE company_like DROP FOREIGN KEY FK_EF0E5A5D979B1AD6');
        $this->addSql('ALTER TABLE approved_company DROP FOREIGN KEY FK_69CCB46B979B1AD6');
        $this->addSql('ALTER TABLE use_fund DROP FOREIGN KEY FK_43BEADD4979B1AD6');
        $this->addSql('ALTER TABLE company_domain DROP FOREIGN KEY FK_9A367A7E979B1AD6');
        $this->addSql('ALTER TABLE approved_company_domain DROP FOREIGN KEY FK_3CBB0DA7115F0EE5');
        $this->addSql('ALTER TABLE company_domain DROP FOREIGN KEY FK_9A367A7E115F0EE5');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6498BAC62AF');
        $this->addSql('ALTER TABLE approved_company DROP FOREIGN KEY FK_69CCB46B8BAC62AF');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F8BAC62AF');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE fond_phase DROP FOREIGN KEY FK_8C7613BF99091188');
        $this->addSql('ALTER TABLE log_download DROP FOREIGN KEY FK_164949AF8F7B22CC');
        $this->addSql('ALTER TABLE block_published DROP FOREIGN KEY FK_58D3E002C4663E4');
        $this->addSql('ALTER TABLE article_published DROP FOREIGN KEY FK_B20930337294869C');
        $this->addSql('ALTER TABLE block DROP FOREIGN KEY FK_831B97227294869C');
        $this->addSql('ALTER TABLE page_published DROP FOREIGN KEY FK_53D2DFD8C4663E4');
        $this->addSql('ALTER TABLE block DROP FOREIGN KEY FK_831B9722C4663E4');
        $this->addSql('ALTER TABLE event_published DROP FOREIGN KEY FK_EEA95E2A12469DE2');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA712469DE2');
        $this->addSql('ALTER TABLE block_published DROP FOREIGN KEY FK_58D3E00271F7E88B');
        $this->addSql('ALTER TABLE event_like DROP FOREIGN KEY FK_B3A80C1871F7E88B');
        $this->addSql('ALTER TABLE event_view DROP FOREIGN KEY FK_E136E72571F7E88B');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E6612469DE2');
        $this->addSql('ALTER TABLE article_published DROP FOREIGN KEY FK_B209303312469DE2');
        $this->addSql('ALTER TABLE page_published DROP FOREIGN KEY FK_53D2DFD812469DE2');
        $this->addSql('ALTER TABLE page DROP FOREIGN KEY FK_140AB62012469DE2');
        $this->addSql('ALTER TABLE block_published DROP FOREIGN KEY FK_58D3E0027294869C');
        $this->addSql('ALTER TABLE article_like DROP FOREIGN KEY FK_1C21C7B27294869C');
        $this->addSql('ALTER TABLE article_view DROP FOREIGN KEY FK_4EBF2C8F7294869C');
        $this->addSql('ALTER TABLE event_published DROP FOREIGN KEY FK_EEA95E2A71F7E88B');
        $this->addSql('ALTER TABLE block DROP FOREIGN KEY FK_831B972271F7E88B');
        $this->addSql('DROP TABLE contributor');
        $this->addSql('DROP TABLE project_finance');
        $this->addSql('DROP TABLE background_slider');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE business_model');
        $this->addSql('DROP TABLE step');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE reassurance');
        $this->addSql('DROP TABLE company_document');
        $this->addSql('DROP TABLE global_document');
        $this->addSql('DROP TABLE fond');
        $this->addSql('DROP TABLE fond_gestionnaire');
        $this->addSql('DROP TABLE fond_secteur');
        $this->addSql('DROP TABLE fond_phase');
        $this->addSql('DROP TABLE fond_financement_type');
        $this->addSql('DROP TABLE fond_depenses_type');
        $this->addSql('DROP TABLE company_comment');
        $this->addSql('DROP TABLE financement_type');
        $this->addSql('DROP TABLE company_like');
        $this->addSql('DROP TABLE document_type');
        $this->addSql('DROP TABLE reassurance_col');
        $this->addSql('DROP TABLE message_response');
        $this->addSql('DROP TABLE slider');
        $this->addSql('DROP TABLE log_download');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE approved_avantage');
        $this->addSql('DROP TABLE fond_type');
        $this->addSql('DROP TABLE sales_channels');
        $this->addSql('DROP TABLE sector');
        $this->addSql('DROP TABLE approved_gallery_photo');
        $this->addSql('DROP TABLE depenses_type');
        $this->addSql('DROP TABLE approved_use_fund');
        $this->addSql('DROP TABLE montant');
        $this->addSql('DROP TABLE approved_document');
        $this->addSql('DROP TABLE team_member');
        $this->addSql('DROP TABLE approved_company');
        $this->addSql('DROP TABLE approved_company_domain');
        $this->addSql('DROP TABLE secteur');
        $this->addSql('DROP TABLE approved_project');
        $this->addSql('DROP TABLE approved_project_sales_channels');
        $this->addSql('DROP TABLE approved_project_sector');
        $this->addSql('DROP TABLE approved_project_business_model');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_sales_channels');
        $this->addSql('DROP TABLE project_sector');
        $this->addSql('DROP TABLE project_business_model');
        $this->addSql('DROP TABLE eligibilite_critere');
        $this->addSql('DROP TABLE seo');
        $this->addSql('DROP TABLE request_documentation');
        $this->addSql('DROP TABLE request_documentation_document_type');
        $this->addSql('DROP TABLE contact_info');
        $this->addSql('DROP TABLE garanties_block');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE use_fund');
        $this->addSql('DROP TABLE earned');
        $this->addSql('DROP TABLE company_comment_response');
        $this->addSql('DROP TABLE approved_company_document');
        $this->addSql('DROP TABLE gestionnaire');
        $this->addSql('DROP TABLE project_like');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE approved_project_finance');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE company_domain');
        $this->addSql('DROP TABLE video');
        $this->addSql('DROP TABLE mail_sended');
        $this->addSql('DROP TABLE email_template');
        $this->addSql('DROP TABLE testimonial');
        $this->addSql('DROP TABLE approved_team_member');
        $this->addSql('DROP TABLE domain');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE header');
        $this->addSql('DROP TABLE comment_ca_marche_block');
        $this->addSql('DROP TABLE gallery_photo');
        $this->addSql('DROP TABLE avantage');
        $this->addSql('DROP TABLE approved_service');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE phase');
        $this->addSql('DROP TABLE funding_objective');
        $this->addSql('DROP TABLE request_doc_accepted');
        $this->addSql('DROP TABLE tools');
        $this->addSql('DROP TABLE company_faq');
        $this->addSql('DROP TABLE ip');
        $this->addSql('DROP TABLE block_published');
        $this->addSql('DROP TABLE page_published');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE event_like');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE category_event');
        $this->addSql('DROP TABLE event_published');
        $this->addSql('DROP TABLE article_like');
        $this->addSql('DROP TABLE article_view');
        $this->addSql('DROP TABLE category_article');
        $this->addSql('DROP TABLE event_view');
        $this->addSql('DROP TABLE category_page');
        $this->addSql('DROP TABLE row_published');
        $this->addSql('DROP TABLE article_published');
        $this->addSql('DROP TABLE block');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE `row`');
        $this->addSql('DROP TABLE offer_request');
    }
}
